### PR TITLE
Fixed typedef error related bug.

### PR DESCRIPTION
**Pull request by zsoltbalint**

### CODE REVIEW

**Comment by norio-nomura** [comment]
Thanks for doing this.
I resolved build failure by another approach.
Please check latest master.

**Comment by zsoltbalint** [comment]
Cool, so are you planning to continue the development? 😃

**Comment by norio-nomura** [comment]
Maybe. But I don't think there is a lot of room for improvement under current limited functionality of Xcode Source Editor Extension.

**Comment by zsoltbalint** [comment]
I understand. Last question. How and why the `@escaping` keyword solved the error here?

**Comment by norio-nomura** [comment]
This article would help you. https://oleb.net/blog/2016/10/optional-non-escaping-closures/
Your patch did implicitly specifying `@escaping` by using `ImplicitlyUnwrappedOptional`.
My fix was suggested by Xcode 8.1 beta 3 that clever than Xcode 8.0.

**Comment by zsoltbalint** [comment]
That's a good article, thank you!

**Pull request closed without merging**
